name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

    
jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest

    steps:
      -name: Checkout
        uses: actions:checkout@v4
      - name: Containerized Build
        uses: ./.github/actions/my-container-action
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}
      
  

      
  deploy:
    needs: build
    name: Deploy App to Azure
    runs-on: ubuntu-latest
    steps: 
    -name: deploy to azure web app
    uses: azure/appservice-actions/webapp@master
    with:
      app-name: latesetversion
      publish-profile: {{secrets.azureWebAppPublishProfile}}
